### ISSUE TITLE
Configrd - Your own config & secrets management server

### ISSUE THREAD

**Issue by kkarski** [Atarity/deploy-your-own-saas#12]
Docs: https://configrd.io
GitHub: https://github.com/configrd/configrd-service

## Criteria
1. Every day needs;
1. Open-source and free;
1. Server-side which is suitable for common VPS;
1. You are the only who control and being responsible of your data.

**Comment by Atarity** [comment]
Interesting and well-documented product, but I can not consider it as everyday needs for common consumers.
