### ISSUE TITLE
Jitsi - your own video conference Software

### ISSUE THREAD

**Issue by fuu0** [Atarity/deploy-your-own-saas#16]
https://jitsi.org/
just a webinterface - type in a meetingroom name, invite people, talk, leave, done.
No external Fonts, no Browser Plugin

## Criteria
1. Every day needs;
1. Open-source and free;
1. Server-side which is suitable for common VPS;
1. You are the only who control and being responsible of your data.

**Comment by Atarity** [comment]
Added. Thanks.
