### ISSUE TITLE
Seafile Cloud Storage

### ISSUE THREAD

**Issue by hg2s** [Atarity/deploy-your-own-saas#18]
[Seafile](https://www.seafile.com/en/download/) is an open source file sync & share solution designed for high reliability, performance and productivity. Sync, share and collaborate across devices and teams. Build your team's knowledge base with Seafile's built-in Wiki feature. The Community Edition is free and allows unlimited users.

Client software (Mac, Windows, Linux, terminal) includes a desktop sync application, a desktop drive client, and mobile apps for iOS and Android. 

More info [here](https://www.seafile.com/en/home/).

**Comment by Atarity** [comment]
Added, thanks!
