### ISSUE TITLE
Sourcehut - free oss code hosting

### ISSUE THREAD

**Issue by DenSA-Inc** [Atarity/deploy-your-own-saas#19]
[Sourcehut](https://sourcehut.org/) is as free and minimalistic hosting-platform for git- and hg-repositories. Feature-wise it's comparable to gitlab-ce, but more composable.

## Criteria
1. Every day needs; 
1. Open-source and free;
1. Server-side which is suitable for common VPS;
1. You are the only who control and being responsible of your data.

**Comment by Atarity** [comment]
Interesting, but owner consider it as alpha. I'll check it later.
