### ISSUE TITLE
OnlyOffice Collaborative Office Suite

### ISSUE THREAD

**Issue by hg2s** [Atarity/deploy-your-own-saas#20]
[OnlyOffice](https://www.onlyoffice.com/) is an integrated collaboration platform that offers mail, CRM, projects, calendar and more. A free open source [Community Edition](https://www.onlyoffice.com/download.aspx) is available that runs under Docker. 

Fully compatible with Microsoft Office Word, Excel and PowerPoint the online document editor can be integrated with [Seafile](https://www.seafile.com/en/home/), for example, to provide collaborative document sharing and editing. 

Standalone [desktop editors](https://www.onlyoffice.com/download-desktop.aspx) are available for Mac, Windows and Linux.

**Comment by Atarity** [comment]
Added, thanks.
