### ISSUE TITLE
Create "Deploy your own Fake Data Server" Section

### ISSUE THREAD

**Issue by k4m4** [Atarity/deploy-your-own-saas#31]
In my opinion, a section named _Deploy your own `Fake Data Server`_ would be a good addition to this list. Possible projects for this section would include:
- [`json-server`](https://github.com/typicode/json-server)
- [`mockserver`](https://github.com/mock-server/mockserver)
- [`micro-jaymock`](https://github.com/unmock/micro-jaymock)

**Comment by Atarity** [comment]
Can not consider fake data server as a personal EDC. Sorry, didn't fit to the list.

**Comment by k4m4** [comment]
Totally makes sense. Thank you for the feedback, @Atarity!
