### ISSUE TITLE
Mailu

### ISSUE THREAD

**Issue by arretevad** [Atarity/deploy-your-own-saas#38]
## Mailu
- Another email stack. 
- https://mailu.io
- FOSS, https://mailu.io/1.7/general.html
- Docker based, highly configurable and simple. Personally I found Mailcow a little intimidating. Mailu is very accessible. 

## Criteria
1. Every day needs (mostly for personal usage);
1. Open-source and free;
1. Server-side which is suitable for common VPS;
1. You are the only who control and being responsible of your data.

## Please, NO
1. Early stage/alpha/yesterday started products;
1. Dead or abandoned products;
1. Community Edition with reduced list of features (users limit, no your own domain, etc).

## Hell, YES
1. Products with tutorials and how-to's;
1. Community-driven products;
1. Products with GitHub/GitLab/Bitbucket open repos.

**Comment by Atarity** [comment]
Added. Thanks.
