### ISSUE TITLE
Gaming group voice

### ISSUE THREAD

**Issue by itsTurnip** [Atarity/deploy-your-own-saas#4]
## Criteria

- [x] Every day needs;
- [x] Open-source and free;
- [x] Server-side which is suitable for common VPS;
- [x] You are the only who control and being responsible of your data.

The best analogue of teamspeak or discord is [Mumble](https://github.com/mumble-voip/mumble). It's quite easy to deploy and suitable for VPSs.

**Comment by Atarity** [comment]
Done. Thanks!
