### ISSUE TITLE
AzuraCast

### ISSUE THREAD

**Issue by kerbyj** [Atarity/deploy-your-own-saas#58]
AzuraCast is a free and open-source self hosted web radio management suite. 

Main site - https://www.azuracast.com/
Installation guide - https://docs.azuracast.com/en/getting-started/installation

Unlike many other projects this project is really launched via docker without hard skills)

**Comment by Atarity** [comment]
Thanks 👍. Added in [dd10c89](https://github.com/Atarity/deploy-your-own-saas/commit/dd10c89aac1e645ba22e528416ff274c2bbe25e3)
